spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_CLUSTER}.dvmgf.mongodb.net/${MONGO_DB_NAME}?retryWrites=true&w=majority
      auto-index-creation: true
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
            repository:
              Query: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  show-actuator: true
  show-login-endpoint: true
